config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:show] do
    resources :users, only: [:index, :edit, :update]
  end
  get 'admin/:id/booklist', to: 'admin#booklist', as: 'admin_booklist'
  resources :genres
  resources :authors
  post 'carts/:id/checkout', to: 'carts#checkout', as: 'checkout'
  get 'site/home'
  root 'site#home'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users, only: [:show, :update]
  resources :cart_books
  resources :carts, only: :show
  resources :books

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :books
  has_many :authors, through: :books

  validates :name, presence: true, uniqueness: true

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:id, :name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/index.html.erb
<h1>Book Genres</h1>
<ul>
  <% @genres.each do |genre| %>
    <li><%= link_to genre.name, genre_path(genre) %></li>
  <% end %>
</ul>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>
<label>Books: </label>
<ul>
  <% @genre.books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
  <% end %>
</ul>
<br>
<label>Authors: </label>
<ul>
  <% @genre.authors.uniq.each do |author| %>
    <li><%= link_to author.name, author_path(author) %></li>
  <% end %>
</ul>