config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:show] do
    resources :users, only: [:index, :edit, :update]
  end
  get 'admin/:id/booklist', to: 'admin#booklist', as: 'admin_booklist'
  resources :genres
  resources :authors
  post 'carts/:id/checkout', to: 'carts#checkout', as: 'checkout'
  get 'site/home'
  root 'site#home'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users, only: [:show, :update]
  resources :cart_books
  resources :carts, only: :show
  resources :books

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  has_many :genres, through: :books

  validates :name, presence: true, uniqueness: true
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :genre

  validates :title, presence: true, uniqueness: true
  scope :available_books, -> { where('inventory > 0') }

  def author_attribute=(author_attribute)
    author = Author.find_or_create_by(author_attribute)
    self.author = author
  end

  def genre_attribute=(genre_attribute)
    genre = Genre.find_or_create_by(genre_attribute)
    self.genre = genre
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_books
  has_many :books, through: :cart_books

  def add_item(book_id)
    cart_book = self.cart_books.find_by(book_id: book_id)
    if cart_book
      cart_book.quantity += 1
    else
      cart_book = self.cart_books.build(cart_id: self.id, book_id: book_id)
    end
    cart_book
  end

  def total
    cart_total = 0
    self.cart_books.each do |cart_book|
      cart_total += cart_book.book.price.to_f/100 * cart_book.quantity
    end
    cart_total
  end
end

app/models/cart_book.rb
class CartBook < ActiveRecord::Base
  belongs_to :cart
  belongs_to :book
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :books
  has_many :authors, through: :books

  validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :
  devise :database_authenticatable, :registerable, :recoverable,
  :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :carts
  belongs_to :current_cart, :class_name => "Cart"
  has_many :purchase_history, :class_name => "Cart"

  def create_cart
    self.current_cart ||= Cart.create
    self.current_cart.user_id = self.id
    self.current_cart.save
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def current_cart_purchase(current_cart)
    
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def show
    admin_only
  end
  def booklist
    admin_only
    @books = Book.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    admin_only
    @book = Book.new(author_id: params[:author_id])
  end

  def create
    admin_only
    @book = Book.find_by(title: params[:book][:title])
    if @book
      flash[:notice] = "Book already exists"
      redirect_to new_book_path
    else
      @book = Book.create(book_params)
      @book.author = Author.find(params[:book][:author_id]) if !params[:book][:author_id].empty?
      @book.genre = Genre.find(params[:book][:genre_id]) if !params[:book][:genre_id].empty?
      @book.save
      @book.author.save
      @book.genre.save
      flash[:notice] = "#{@book.title} successfully added."
      redirect_to admin_path(current_user)
    end
  end

  def index
    @books = Book.available_books
    respond_to do |format|
      format.html
      format.json { render json: @books }
    end
  end

  def show
    @book = Book.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render json: @book, adapter: :json}
    end
  end

  def edit
    admin_only
    @book = Book.find(params[:id])
  end

  def update
    admin_only
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "#{@book.title} successfully updated!"
      redirect_to admin_path(current_user)
    else
      flash[:alert] = "There was a problem"
      redirect_to edit_book_path(@book)
    end
  end

  def destroy
    admin_only
    @book = Book.find(params[:id])
    book_title = @book.title
    @book.delete
    respond_to do |format|
      format.html {render html: "admin/#{current_user.id}"}
      format.json {render json: @book}
    end
  end

  def book_params
    params.require(:book).permit(:title, :price, :inventory, :author_id, :genre_id, author_attribute: [:name], genre_attribute: [:name])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = current_user.current_cart
    respond_to do |format|
      format.html
      format.json {render json: @cart, adapter: :json }
    end
  end

  def checkout
    @cart = Cart.find(params[:id])
    @cart.cart_books.each do |cart_book|
      Book.find(cart_book.book_id).decrement(:inventory, cart_book.quantity).save
    end
    current_user.current_cart = nil
    current_user.save
    flash[:notice] = "Thank you for your puchase!"
    redirect_to root_path
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    if user_signed_in?
      if current_user.admin?
        redirect_to admin_path(current_user)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user.admin?
      @users = User.all
      respond_to do |format|
        format.html { render :index }
        format.json {render json: @users, adapter: :json }
      end
    else
      flash[:alert] = "Access Denied."
      redirect_to root_path
    end
    admin_only
    @users = User.all
  end

  def show
    @user = current_user if user_signed_in?
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @user, adapter: :json }
    end
  end

  def edit
    admin_only
    @user = User.find(params[:id])
  end

  def update
    admin_only
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "Successfully Updated #{@user.email}."
    redirect_to admin_users_path(current_user)
  end

  def user_params
    params.require(:user).permit(:admin)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def list_label(starting_letter)
    content_tag(:h2) do
      starting_letter.capitalize
    end
  end

  def list_by_abc(starting_letter, list)
    content_tag(:ul) do
      list.collect do |list_item|
        if list_item.title.first.capitalize.include?(starting_letter.capitalize)
          list_link = link_to list_item.title, book_path(list_item)
          list_edit_link = link_to "Edit #{list_item.title}", edit_book_path(list_item)
          concat content_tag(:li, list_link)
          if user_signed_in?
            if current_user.admin?
              concat content_tag(:li, list_edit_link)
            end
          end
        end
      end
    end
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
  def author_list_by_abc(starting_letter, list)
    content_tag(:ul) do
      list.collect do |list_item|
        if list_item.name.first.capitalize.include?(starting_letter.capitalize)
          list_link = link_to list_item.name, author_path(list_item)
          concat content_tag(:li, list_link)
        end
      end
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper

  def book_list
    content_tag(:ul) do
      yield
    end
  end

end

app/helpers/cart_books_helper.rb
module CartBooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/booklist.html.erb
<h1>Book List</h1>
<table border="1" style="width:100%">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Price</th>
      <th>Inventory</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% Book.order(title: :asc).each do |book| %>
      <tr>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= link_to book.author.name, author_path(book.author) %></td>
        <td><%= link_to book.genre.name, genre_path(book.genre) %></td>
        <td><%= number_to_currency(book.price.to_f/100) %></td>
        <td><%= book.inventory %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Delete", book_path(book), remote: true, method: 'DELETE', id: book.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/show.html.erb
<h1>Admin <%= current_user.email %></h1>
<h3>Admin Tools</h3>
<%= link_to "New Book", new_book_path, id: "new_book" %><br>
<%= link_to "Book List", admin_booklist_path(current_user) %>

app/views/layouts/_admin_header.html.erb
<%= link_to "#{current_user.email}", admin_path(current_user) %>
<%= link_to "Users", admin_users_path(current_user) %>
<%= link_to "Books", books_path %>
<%= link_to "Log Out", destroy_user_session_path, method: :delete %>

app/views/layouts/_header.html.erb
<%= link_to "Home", root_path %>
<% if user_signed_in? %>
  <%= link_to "#{current_user.email}", user_path(current_user) %>
<% end %>
<%= link_to "Books", books_path %>
<%= link_to "Genres", genres_path %>
<%= link_to "Authors", authors_path %>
<% if !user_signed_in? %>
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
  <%= link_to "Sign In", new_user_session_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
<% else %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <a href="#" id="cart">Cart</a>
  <%= link_to "Sign Out", destroy_user_session_path, method: 'DELETE' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryRailsV000</title>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <% if !current_user.admin? %>
    <div class="">
      <%= render 'layouts/header' %>
    </div>
    <% else %>
    <div class="">
      <%= render 'layouts/admin_header' %>
    </div>
    <% end %>
  <% else %>
  <div class="">
    <%= render 'layouts/header' %>
  </div>
  <% end %>
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
<%= yield %>

</body>
</html>