config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:show] do
    resources :users, only: [:index, :edit, :update]
  end
  get 'admin/:id/booklist', to: 'admin#booklist', as: 'admin_booklist'
  resources :genres
  resources :authors
  post 'carts/:id/checkout', to: 'carts#checkout', as: 'checkout'
  get 'site/home'
  root 'site#home'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users, only: [:show, :update]
  resources :cart_books
  resources :carts, only: :show
  resources :books

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_books
  has_many :books, through: :cart_books

  def add_item(book_id)
    cart_book = self.cart_books.find_by(book_id: book_id)
    if cart_book
      cart_book.quantity += 1
    else
      cart_book = self.cart_books.build(cart_id: self.id, book_id: book_id)
    end
    cart_book
  end

  def total
    cart_total = 0
    self.cart_books.each do |cart_book|
      cart_total += cart_book.book.price.to_f/100 * cart_book.quantity
    end
    cart_total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = current_user.current_cart
    respond_to do |format|
      format.html
      format.json {render json: @cart, adapter: :json }
    end
  end

  def checkout
    @cart = Cart.find(params[:id])
    @cart.cart_books.each do |cart_book|
      Book.find(cart_book.book_id).decrement(:inventory, cart_book.quantity).save
    end
    current_user.current_cart = nil
    current_user.save
    flash[:notice] = "Thank you for your puchase!"
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<h1><%= current_user.email %>'s Cart</h1>


<% @cart.cart_books.each do |cart_book| %>
  <p><%= link_to cart_book.book.title, book_path(cart_book.book) %> | <%= number_to_currency(cart_book.book.price.to_f/100) %> | Quantity: <%= cart_book.quantity %> | <%= link_to "Remove Book", cart_book_path(cart_book), method: 'DELETE' %></p>
<% end %>
<br>
<p>-----------------</p>
<label>Total: </label>
<%= number_to_currency(@cart.total) %>
<br>
<%= button_to "Checkout", checkout_path %>